#!/usr/bin/env python3
"""Generate the Desk-Mixer wire-protocol bindings for both firmware and app.

`Tools/protocol.toml` is the single source of truth. This script emits:

  Firmware/include/link/protocol_gen.h            (house Doxygen style)
  App/src/desk_mixer_app/device/protocol_gen.py

Neither generated file may be edited by hand.

Usage:
    python3 Tools/generate_protocol.py            # write the files
    python3 Tools/generate_protocol.py --check    # exit 1 if they are out of date

Requires only the standard library (tomllib, Python 3.11+).
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "Tools" / "protocol.toml"

# Both outputs are parked until each side decides where its generated file lives.
# Point these at real paths to switch generation back on, e.g.
#   H_OUT  = ROOT / "Firmware" / "include" / "link" / "protocol_gen.h"
#   PY_OUT = ROOT / "App" / "src" / "desk_mixer_app" / "device" / "protocol_gen.py"
# render_header() and render_python() are complete and need no changes.
#
# With both parked, --check still validates the spec itself, so CI keeps its
# guard against duplicate opcodes and malformed entries.
H_OUT = None
PY_OUT = None

WIDTH = 100
STAR = "/" + "*" * (WIDTH - 2) + "/"
DASH = "/*" + "-" * (WIDTH - 4) + "*/"


def band(label: str, source: bool) -> str:
    """Render a house-style section banner line."""
    return (("/* " if source else "// ") + label).ljust(WIDTH - 2) + "*/"


def file_header(name: str, brief: list[str]) -> str:
    """Render the house-style Doxygen file header block."""
    lines = [STAR, "/**", f" * @file {name}", " * @author  generated by Tools/generate_protocol.py",
             f" * @brief {brief[0]}"]
    lines += [f" *        {b}" for b in brief[1:]]
    lines += [" *", " * @copyright Copyright (c) 2026", " *", " */", STAR]
    return "\n".join(lines)


def load() -> dict:
    with SPEC.open("rb") as fh:
        return tomllib.load(fh)


def render_header(spec: dict) -> str:
    fr = spec["framing"]
    out: list[str] = [
        file_header("protocol_gen.h", [
            "AUTO-GENERATED from Tools/protocol.toml -- DO NOT EDIT BY HAND.",
            "Edit Tools/protocol.toml and re-run Tools/generate_protocol.py instead.",
        ]),
        "",
        "#ifndef LINK_PROTOCOL_GEN_H",
        "#define LINK_PROTOCOL_GEN_H",
        "",
        DASH, band("HEADERS", False), DASH, "",
        "#include <stdint.h>",
        "",
        DASH, band("GLOBAL VARIABLES", False), DASH, "",
        f"#define PROTOCOL_VERSION {spec['version']}",
        f"#define PROTOCOL_SYNC 0x{fr['sync']:02X}",
        f"#define PROTOCOL_MAX_PAYLOAD {fr['max_payload']}",
        "",
        "// Frame overhead: sync + opcode + length(2) + crc(2).",
        "#define PROTOCOL_OVERHEAD 6",
        "#define PROTOCOL_MAX_FRAME (PROTOCOL_MAX_PAYLOAD + PROTOCOL_OVERHEAD)",
        "",
        DASH, band("CLASS DECLARATIONS", False), DASH, "",
    ]

    out += _c_enum("ProtocolCommand", "Host -> device opcodes.",
                   [(f"CMD_{c['name']}", c["code"], c["doc"]) for c in spec["commands"]])
    out += _c_enum("ProtocolEvent", "Device -> host opcodes.",
                   [(f"EVT_{e['name']}", e["code"], e["doc"]) for e in spec["events"]])

    for ename, edef in spec["enums"].items():
        prefix = ename.upper()
        out += _c_enum(f"Protocol{ename}", edef["doc"],
                       [(f"{prefix}_{v}", val, "") for v, val in edef["values"].items()])

    out += [DASH, band("FUNCTION DECLARATIONS", False), DASH, "", "", "",
            "#endif // LINK_PROTOCOL_GEN_H", ""]
    return "\n".join(out)


def _c_enum(name: str, doc: str, members: list[tuple[str, int, str]]) -> list[str]:
    """Render a C enum with values aligned into a column.

    Member documentation goes on its own line above the enumerator rather than
    trailing it, so no line can exceed the 100-column house limit however long
    the description is.
    """
    pad = max(len(m[0]) for m in members)
    out = [f"// {doc}", f"enum {name} {{"]
    for i, (mname, val, mdoc) in enumerate(members):
        if mdoc:
            if i:
                out.append("")
            out += _wrap_comment(mdoc, indent=4)
        out.append(f"    {mname.ljust(pad)} = 0x{val:02X},")
    out += ["};", ""]
    return out


def _wrap_comment(text: str, indent: int) -> list[str]:
    """Wrap `text` as // comment lines that fit inside the 100-column limit."""
    prefix = " " * indent + "// "
    limit = WIDTH - len(prefix)
    words, lines, cur = text.split(), [], ""
    for w in words:
        if cur and len(cur) + 1 + len(w) > limit:
            lines.append(prefix + cur)
            cur = w
        else:
            cur = f"{cur} {w}".strip()
    if cur:
        lines.append(prefix + cur)
    return lines


def _c_prefix(enum_name: str) -> str:
    """Map an enum name to its C member prefix, e.g. Transport -> TRANSPORT."""
    return enum_name.upper()


def render_python(spec: dict) -> str:
    fr = spec["framing"]
    out: list[str] = [
        '"""AUTO-GENERATED from Tools/protocol.toml -- DO NOT EDIT BY HAND.',
        "",
        "Edit Tools/protocol.toml and re-run Tools/generate_protocol.py instead.",
        "",
        "Wire-protocol constants shared with the Teensy firmware. The firmware's",
        "matching definitions live in Firmware/include/link/protocol_gen.h.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from enum import IntEnum",
        "",
        f"PROTOCOL_VERSION = {spec['version']}",
        f"PROTOCOL_SYNC = 0x{fr['sync']:02X}",
        f"PROTOCOL_MAX_PAYLOAD = {fr['max_payload']}",
        "",
        "#: sync + opcode + length(2) + crc(2)",
        "PROTOCOL_OVERHEAD = 6",
        "PROTOCOL_MAX_FRAME = PROTOCOL_MAX_PAYLOAD + PROTOCOL_OVERHEAD",
        "",
        "",
        "class Command(IntEnum):",
        '    """Host -> device opcodes."""',
        "",
    ]
    for c in spec["commands"]:
        out.append(f"    #: {c['doc']}")
        out.append(f"    {c['name']} = 0x{c['code']:02X}")
    out += ["", "", "class Event(IntEnum):", '    """Device -> host opcodes."""', ""]
    for e in spec["events"]:
        out.append(f"    #: {e['doc']}")
        out.append(f"    {e['name']} = 0x{e['code']:02X}")

    for ename, edef in spec["enums"].items():
        out += ["", "", f"class {ename}(IntEnum):", f'    """{edef["doc"]}"""', ""]
        for vname, val in edef["values"].items():
            out.append(f"    {vname} = 0x{val:02X}")
    out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify generated files are up to date; do not write")
    args = ap.parse_args()

    spec = load()
    codes = [c["code"] for c in spec["commands"]] + [e["code"] for e in spec["events"]]
    if len(codes) != len(set(codes)):
        print("error: duplicate opcode in Tools/protocol.toml", file=sys.stderr)
        return 2

    targets = {}
    if H_OUT is not None:
        targets[H_OUT] = render_header(spec)
    if PY_OUT is not None:
        targets[PY_OUT] = render_python(spec)

    if not targets:
        # Spec still gets validated above; there is simply nothing to emit yet.
        n_cmd, n_evt = len(spec["commands"]), len(spec["events"])
        print(f"spec OK — {n_cmd} commands, {n_evt} events, {len(codes)} unique opcodes")
        print("generation is parked: set H_OUT / PY_OUT to enable output")
        return 0

    if args.check:
        stale = [p for p, text in targets.items()
                 if not p.exists() or p.read_text() != text]
        if stale:
            for p in stale:
                print(f"out of date: {p.relative_to(ROOT)}", file=sys.stderr)
            print("\nrun: python3 Tools/generate_protocol.py", file=sys.stderr)
            return 1
        print("protocol bindings are up to date")
        return 0

    for path, text in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
